/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEaddressStruct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEaddressStructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface DocumentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAccess"
      | "documentExists"
      | "getDocument"
      | "getGrantKey"
      | "getLastAccessResult"
      | "getOwnerKey"
      | "getQueryAudit"
      | "getUploadedAt"
      | "grantAccess"
      | "logQueryAuth"
      | "registerDocument"
      | "revokeAccess"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "DocumentRegistered"
      | "QueryLogged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkAccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "documentExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocument",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrantKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastAccessResult",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQueryAudit",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUploadedAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BytesLike, AddressLike, InEuint64Struct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logQueryAuth",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDocument",
    values: [BytesLike, InEuint64Struct, InEaddressStruct, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "documentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGrantKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastAccessResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQueryAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUploadedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logQueryAuth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [docId: BytesLike, grantee: AddressLike];
  export type OutputTuple = [docId: string, grantee: string];
  export interface OutputObject {
    docId: string;
    grantee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [docId: BytesLike, grantee: AddressLike];
  export type OutputTuple = [docId: string, grantee: string];
  export interface OutputObject {
    docId: string;
    grantee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentRegisteredEvent {
  export type InputTuple = [docId: BytesLike, ipfsCid: BytesLike];
  export type OutputTuple = [docId: string, ipfsCid: string];
  export interface OutputObject {
    docId: string;
    ipfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QueryLoggedEvent {
  export type InputTuple = [docId: BytesLike, queryHash: BytesLike];
  export type OutputTuple = [docId: string, queryHash: string];
  export interface OutputObject {
    docId: string;
    queryHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentVault extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentVault;
  waitForDeployment(): Promise<this>;

  interface: DocumentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAccess: TypedContractMethod<[docId: BytesLike], [string], "nonpayable">;

  documentExists: TypedContractMethod<[docId: BytesLike], [boolean], "view">;

  getDocument: TypedContractMethod<
    [docId: BytesLike],
    [[string, boolean] & { ipfsCid: string; exists: boolean }],
    "view"
  >;

  getGrantKey: TypedContractMethod<[docId: BytesLike], [string], "view">;

  getLastAccessResult: TypedContractMethod<
    [docId: BytesLike, user: AddressLike],
    [string],
    "view"
  >;

  getOwnerKey: TypedContractMethod<[docId: BytesLike], [string], "view">;

  getQueryAudit: TypedContractMethod<
    [docId: BytesLike, queryHash: BytesLike],
    [string],
    "view"
  >;

  getUploadedAt: TypedContractMethod<[docId: BytesLike], [string], "view">;

  grantAccess: TypedContractMethod<
    [
      docId: BytesLike,
      grantee: AddressLike,
      encExpiry: InEuint64Struct,
      granteeEncKey: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  logQueryAuth: TypedContractMethod<
    [docId: BytesLike, queryHash: BytesLike],
    [string],
    "nonpayable"
  >;

  registerDocument: TypedContractMethod<
    [
      docId: BytesLike,
      encTimestamp: InEuint64Struct,
      encOwner: InEaddressStruct,
      ipfsCid: BytesLike,
      encryptedKey: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [docId: BytesLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAccess"
  ): TypedContractMethod<[docId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "documentExists"
  ): TypedContractMethod<[docId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getDocument"
  ): TypedContractMethod<
    [docId: BytesLike],
    [[string, boolean] & { ipfsCid: string; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGrantKey"
  ): TypedContractMethod<[docId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getLastAccessResult"
  ): TypedContractMethod<
    [docId: BytesLike, user: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerKey"
  ): TypedContractMethod<[docId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getQueryAudit"
  ): TypedContractMethod<
    [docId: BytesLike, queryHash: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUploadedAt"
  ): TypedContractMethod<[docId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [
      docId: BytesLike,
      grantee: AddressLike,
      encExpiry: InEuint64Struct,
      granteeEncKey: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logQueryAuth"
  ): TypedContractMethod<
    [docId: BytesLike, queryHash: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerDocument"
  ): TypedContractMethod<
    [
      docId: BytesLike,
      encTimestamp: InEuint64Struct,
      encOwner: InEaddressStruct,
      ipfsCid: BytesLike,
      encryptedKey: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [docId: BytesLike, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DocumentRegistered"
  ): TypedContractEvent<
    DocumentRegisteredEvent.InputTuple,
    DocumentRegisteredEvent.OutputTuple,
    DocumentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "QueryLogged"
  ): TypedContractEvent<
    QueryLoggedEvent.InputTuple,
    QueryLoggedEvent.OutputTuple,
    QueryLoggedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(bytes32,address)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(bytes32,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "DocumentRegistered(bytes32,bytes32)": TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;
    DocumentRegistered: TypedContractEvent<
      DocumentRegisteredEvent.InputTuple,
      DocumentRegisteredEvent.OutputTuple,
      DocumentRegisteredEvent.OutputObject
    >;

    "QueryLogged(bytes32,bytes32)": TypedContractEvent<
      QueryLoggedEvent.InputTuple,
      QueryLoggedEvent.OutputTuple,
      QueryLoggedEvent.OutputObject
    >;
    QueryLogged: TypedContractEvent<
      QueryLoggedEvent.InputTuple,
      QueryLoggedEvent.OutputTuple,
      QueryLoggedEvent.OutputObject
    >;
  };
}
